server:
  port: 8001

spring:
  data:
    mongodb:
      database: stockDB
      port: 27017
      host: 34.88.24.200
      username: ${mongouser}
      password: ${mongopass}

api :
  priceService : 'http://localhost:8002'
  getPricesByTickers : /price/getByTickers

springdoc:
  api-docs:
    path: /api-docs

logging:
  file:
    path: logs/StockService.log
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


