spring:
  data:
    mongodb:
      database: TestDB
      port: 27018
      host: localhost

api :
  priceService : 'http://localhost:8039'
  getPricesByTickers : /price/getByTickers

logging:
  file:
    path: logs/StockService.log
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


