server:
  port: 8001

spring:
  data:
    mongodb:
      database: stockDB
      port: 27017
      host: 34.88.96.185
      username: ${mongouser}
      password: ${mongopass}

api :
  priceServiceConfig :
    priceService : 'http://localhost:8002'
    getPricesByFigies : /prices
  tinkoffConfig :
    tinkoffService : 'http://localhost:8003'
    getPriceByTicker : /stocks/{ticker}


springdoc:
  api-docs:
    path: /api-docs

logging:
  file:
    path: logs/StockService.log
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


