spring:
  data:
    mongodb:
      database: TestDB
      port: 27018
      host: localhost

logging:
  file:
    path: logs/StockService.log
  level:
    org.springframework.data.mongodb.core: DEBUG


