server:
  port: 8001

spring:
  data:
    mongodb:
      database: stockDB
      port: ${mongo-port}
      host: ${mongo-host}
      username: ${mongouser}
      password: ${mongopass}

api :
  priceServiceConfig :
    priceService : ${gcp-price-service}
    getPricesByFigies : /prices
  tinkoffConfig :
    tinkoffService : ${gcp-tinkoff-ervice}
    getPriceByTicker : /stocks/{ticker}
    getPricesByTickers : /stocks/getStocksByTickers


springdoc:
  api-docs:
    path: /api-docs

logging:
  file:
    path: logs/StockService.log
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


