POST http://localhost:8080/users
Content-Type: application/json

{
  "id" : "2",
  "name" : "Victor Levin",
  "portfolio" : [
    {
      "ticker" : "FXCN",
      "quantity" : 1
    },
    {
      "ticker" : "SBSP",
      "quantity" : 1
    },
    {
      "ticker" : "YNDX",
      "quantity" : 1
    }
  ]
}

###
POST http://localhost:8080/stocks
Content-Type: application/json

{
  "ticker" : "FXCN",
  "name" : "Акции Китая",
  "type" : "ETF",
  "figi" : "14323r23r23r",
  "currency" : "RUB"
}
###
POST http://localhost:8080/stocks
Content-Type: application/json

{
  "ticker" : "YNDX",
  "name" : "Yandex",
  "type" : "STOCK",
  "figi" : "14323r23r35",
  "currency" : "RUB"
}
###
POST http://localhost:8080/stocks
Content-Type: application/json

{
  "ticker" : "SBSP",
  "name" : "Top 500 stocks of USA",
  "type" : "ETF",
  "figi" : "14323r23r232542",
  "currency" : "RUB"
}

###
http://localhost:8080/stocks/FXC

###
http://localhost:8080/users/2

###
http://localhost:8080/statistic/classes/2

###
DELETE http://localhost:8080/stocks/afwaf

###
http://localhost:8080/stocks/
